name: build and deploy infra dev

on: 
  workflow_dispatch: #### To run the workflow manually
  push: 
  pull_request:
    branches:
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 0.14.7

      - name: Terraform Init
        id: init
        if: github.ref != 'refs/heads/main' && (success() || failure())
        run: terraform init

      - name: Terraform Format
        id: fmt
        if: github.ref != 'refs/heads/main'
        run: terraform fmt -check

      - name: List .tfvars files
        run: |
          TFVARS_FILES=$(find ./env -type f -name '*.tfvars')
          echo "$TFVARS_FILES" > tfvars_files.txt
          cat tfvars_files.txt

      - name: Terraform plan
        run: |
          while IFS= read -r tfvars_file; do
            terraform plan -var-file="$tfvars_file"
          done < tfvars_files.txt
    
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          while IFS= read -r tfvars_file; do
            terraform apply --auto-approve -var-file="$tfvars_file"
          done < tfvars_files.txt
